<?php $this->headTitle('Competitor Wireless - Change Password'); ?>

<!-- <tout> -->

<div class="tout">
  <h2> Change Password </h2>
  <div class="brclear"></div>
</div>
<!-- </tout> --> 

<!-- <main> -->
<div class="main">
  <p> Please select a new password for your account.</p>
  <!-- <form> -->
  <form name="changePwForm" id="changePwForm">
    <!-- <fieldset elements> -->
    <fieldset class="find">
      <input type="hidden" name="token" value="<?php echo $this->token; ?>"/>
      Email Address:<br />
      <input type="text" name="email" id="email"/>
      <br/>
      New Password:<br />
      <input type="password" name="pass1" id="pass1"/>
      <br/>
      Confirm Password:<br />
      <input type="password" name="pass2" id="pass2"/>
      <br/>
      <img src="/public/images/buttons/submit.png" border="0" onclick="changePassword();"/>
    </fieldset>
    <!-- </fieldset elements> -->
  </form>
  <!-- </form> -->
  <div class="form" id="responseDiv" style="display:none;"> <br/>
    <br/>
    <p>result</p>
  </div>
  <div class="brclear"></div>
</div>
<!-- </main> --> 

<script type="text/javascript">

function changePassword()
{
	// Validate
	
	var p1 = dojo.byId('pass1').value;
	var p2 = dojo.byId('pass2').value;
	var email = dojo.byId('email').value;
	
	if ((email == '') || (email.match(regexpEmail) == null)) {
		// Bad email address
		var dlg = new dijit.Dialog({
			title: 'Notice',
			content: 'Please enter the EMAIL address you registered with.'
		});
		dlg.show();
		
	} else if (!Util.isAcceptablePassword(p1)) {
		// Bad password
		var dlg = new dijit.Dialog({
			title: 'Notice',
			content: 'Passwords must be at least six characters.'
		});
		dlg.show();
		
	} else if (p1 != p2) {
		// Passwords do not match
		var dlg = new dijit.Dialog({
			title: 'Notice',
			content: 'Passwords must match.'
		});
		dlg.show();
	} else {
		// Everything is cool, do it
		standardWorkingDialog.show();
		
		dojo.xhrPost({
			url: '/ajax/auth/changepassword',
			handleAs: 'json',
			timeout: AJAX_TIMEOUT_MEDIUM,
			form: 'changePwForm',
			
			load: function(response, args) {
				standardWorkingDialog.hide();
				dojo.byId('responseDiv').innerHTML = response.message;
				dojo.byId('changePwForm').style.display = 'none';
				dojo.byId('responseDiv').style.display = '';

			},
			
			error: function(response, args) {
				standardWorkingDialog.hide();
				dojo.byId('responseDiv').innerHTML = response.message;
				dojo.byId('changePwForm').style.display = 'none';
				dojo.byId('responseDiv').style.display = '';
			}
		});
		
	}
	
}

</script>