<?php $this->headTitle('Competitor Wireless - Forgot Password?'); ?>
<!-- <tout> -->

<div class="tout">
  	<h2> Change Password </h2>
  	<div class="brclear"></div>
</div>
<!-- </tout> --> 

<!-- <main> -->
<div class="main">
  	<div id="formDiv" class="form">
    	<p> Please enter the email address you used to register for competitorwireless.com.
      		We will send you an email with instructions for resetting your password.</p>
    	<!-- <form> -->
    	<form name="contactForm" id="contactForm">
      		
        	<!-- <fieldset elements> -->
        	<fieldset class="find">
          		Email Address:
          		<input type="text" name="email" id="email"/>
          		<button data-dojo-type="dijit/form/Button" type="button" class="hand" onclick="submitEmail();" >
        			SUBMIT</button>
          		<div class="brclear"></div>
        	</fieldset>
        	<!-- </fieldset elements> -->
        	<div class="brclear"></div>
      		<!-- </column 1> -->
    	</form>
    	<!-- </form> -->
    	<div class="brclear"></div>
  	</div>
  	<div class="form" id="responseDiv" style="display:none;"> <br/>
    	<br/>
    	<p>Thanks! You will receive an email shortly with instructions for resetting your password.</p>
  	</div>
  	<div class="brclear"></div>
</div>
<!-- </main> --> 
<script type="text/javascript">
function submitEmail()
{
var email = dojo.byId('email').value;
if (email.match(regexpEmail) == null) {
// Not valid email, gripe
var dlg = new dijit.Dialog({
title: 'Notice',
content: 'Please enter a valid EMAIL address.'
});
dlg.show();
} else {
// Is good, do the ajax call.
standardWorkingDialog.show();
dojo.xhrGet({
url: '/ajax/auth/changepwrequest/email/' + email,
handleAs: 'json',
timeout: AJAX_TIMEOUT_MEDIUM,
load: function(response, args) {
standardWorkingDialog.hide();
if (response.status == 'success') {
dojo.byId('formDiv').style.display = 'none';
dojo.byId('responseDiv').style.display = '';
} else {
// TODO: finish
}
},
error: function(response, args) {
standardWorkingDialog.hide();
// TODO: finish
}
});
}
}
</script> 
