<?php $this->headTitle('Runner Tracking - FAQ'); ?>

<!-- <tout> -->

<div class="tout">
  <h2> FAQ</h2>
  <div class="brclear"></div>
</div>
<!-- </tout> --> 

<!-- <main> -->
<div class="main">
	<h2 class="learnMore">What is runner tracking?</h2>
  	<p>Runner tracking is real time location based athlete positioning. 
  	<span style="color:#E9242B; font-weight: bold;">IMPORTANT NOTE: this is an approximation and should not be used as an exact position.</span></p>
  	<h2 class="learnMore">How much does it cost?</h2>
  	<p>You can track up to three people for $2.99.</p>
  	<h2 class="learnMore">When can I sign up?</h2>
  	<p>You can sign up starting approximately a month before the race and up to 15 minutes prior to the earliest race start time.</p>
  	<h2 class="learnMore">Can I change who I'm tracking?</h2>
  	<p>You can update your list of runners up until 15 minutes prior to the earliest race start time. After that you are locked in to 
  		those people and cannot add or change runners even if a runner does not run.</p>
  	<h2 class="learnMore">What should I do if I can't find the correct runner?</h2>
  	<p>Make sure you've tried searching by both bib number and first/last name, and if you still cannot find the correct 
  		runner please contact customer service at: <a href="mailto:cwsupport@competitorwireless.com">cwsupport@competitorwireless.com</a>.</p>
  	<h2 class="learnMore">Can I get a refund if my runner doesn't run?</h2>
  	<p>No, all sales are final and cannot be refunded for any reason including the event a runner does not start, does not finish, 
  		race event suspension, cancellation or bad internet or cellular signals in your area.</p>
  	<h2 class="learnMore">How often does the map update?</h2>
  	<p>The position of the runner will update approximately every two minutes.</p>
  	<h2 class="learnMore">How many split points are there?</h2>
  	<p>For a half marathon there are approximately 5 split points, and for a marathon there are approximately 7 split points, 
  		and these numbers can change depending on the course and cell signals.</p>
  	<h2 class="learnMore">Why hasn't my runner's dot moved in a while?</h2>
 	<p>Since the runner's location on the map is approximate and we don't have gps signals on any runner it could be because of a few reasons.</p> 
  	<ol>
  		<li>The runner could have slowed down from their previous pace and we are holding them at the next split point until they cross it.</li> 
  		<li>The runner may have missed a mat and we are holding them at the closest mat until they cross the next one.</li> 
  		<li>Or something may have happened to the runner which is preventing them from continuing so we are holding them at the closest mat 
  			until they cross another mat.</li>
  	</ol>
  	<h2 class="learnMore">Why is my runner's pace is incorrect at the start of the race?</h2>
  	<p>Until the runner crosses the first mat we don't know their pace so everyone starts out running at a 9:30 minute per mile pace. 
  		Each runner's pace is re-calculated after they cross each mat, so the runner's pace will be updated throughout the race but it is 
  		still an approximation and may not be accurate.</p>
  	<h2 class="learnMore">Can I view a list of all of the split points times?</h2>
 	 <p>Yes. The first screen will display the time elapsed, current pace, and estimated finish time of each of the runners you are tracking. 
  		Once the runner has started, when you click on a runner's name you will go to their approximate location on the map. 
  		If you click on the runner's location on the map you will see a pop-up with the runner's name, and if you click on that 
  		pop-up you will be taken to a summary page with all of the selected runner's split times.</p>
  	<div class="brclear"></div>
</div>
<!-- </main> -->