<?php $this->headTitle('Competitor Wireless - Learn More'); ?>

<!-- <tout> -->

<div class="tout">
  <h2> Learn More</h2>
  <div class="brclear"></div>
</div>
<!-- </tout> --> 

<!-- <main> -->
<div class="main">
  <h2 class="learnMore"> Program Details</h2>
  <p> You can view our <a href="/web/index/terms">Terms of Service</a> here</p>
  <p> All messages will be received from short code: <b>85007. Message and Data Rates may apply</b>, depending on your 
    cellular plan. You can text <strong>HELP</strong> or <strong>STOP</strong> to the short code listed above for more information...</p>
  <h2 class="learnMore"> Pricing:</h2>
  <p> - For a spectator to track a runner: <strong>$2 for the first person you'd like to track, and $1 for each additional person purchased on the same transaction</strong>.  Discount does not apply to separate transactions and can only be applied at time of purchase.<br />
    - For a Runner: You can purchase groups of <strong>5 people to track you for $5 each</strong>, you can purchase just one tracker for $2, and you can also post your split times to Facebook for an additional $1. </p>
  <h2 class="learnMore"> How does this whole thing work?</h2>
  <hr class="dots" />
  <p>We're glad you asked. The short answer... Fairies! No, really, we have fairies that do the work for us. Here's
    a more technical answer for you though if you really want it.</p>
  <p> Each athlete wears a small chip on their shoe. Throughout the race we have timing locations that can read the 
    chip and provide timing data for that athlete, which is how we provide splits throughout the event.</p>
  <p> As you cross the mat and your time is recorded, we send that information to our computers. </p>
  <p> Once we get an athlete's time, we crunch the numbers, and create a text message, which is then delivered to anyone 
    that has opted-in to track you during the event.</p>
  <p> The whole process sounds complicated... and it is. Luckily, we have a lot of smart people working behind the scenes.
    The messages are delivered  within 1 minute of crossing the timing mats. Even though our athlete tracking times are not 'official' it will give you a good idea of how your friends and family are doing 
    during their big event.</p>
  <h2 class="learnMore">Wow, that's amazing! How do I sign up? </h2>
  <hr class="dots" />
  <p>Another great question. To sign up to track a participant, just select the event in the drop down on the left side
    of this page, and then enter the persons first and last name. We'll then try to find the participants registration 
    record in our database, and collect some information from you. That's all there is to it. </p>
  <h2 class="learnMore"> Hmm... What if I'm running and I want people to track me during the race? </h2>
  <hr class="dots" />
  <p> Easy. Just click on the <a href="../events/betrackedstep1"> Be Tracked</a> link here or use the search form on the 
    home page to gets started. We'll take you through a similar process as signing up to track someone, and you'll be able to enter the email addresses of those you want to track you.</p>
  <h2 class="learnMore">Why are you asking for email addresses, I thought this was a text messaging service? </h2>
  <hr class="dots" />
  <p>You are correct, it is. Due to cell phone privacy issues, we need approval of the person receiving 
    the messages before we can deliver anything to their phone. We send email invitations to the addresses you supply, to which 
    the person can click a link in the email and confirm or deny the request you have sent. If they confirm, we then collect some 
    basic information from them to verify their cell phone number, and add them to the list of individuals who will receive updates 
    throughout the race.</p>
  <p>As a participant, you can log into your account at anytime and track the status of your invitations sent out, resend 
    invites, or change/add/delete emails that you've entered in. </p>
  <h2 class="learnMore"> Okay, so this sounds great, what's the catch... How much money are you charging for this service? </h2>
  <hr class="dots" />
  <p> You got us. We are charging for this service. After all, the smart guys that did the work behind the scenes need to eat!
    To track an individual, it'll only cost you $2.00 for the first person and $1 for each additional person you track. </p>
  <p> If you want to pre-pay for others to track you during the race, you can have up to 5 people track you for only $5.00.
    You can purchase multiple 5-packs for only $5.00 each, and have as many people track you as you'd like. Or you can have just one person to track you for $2. For an additional $1 you can 
	also have your split times automatically posted to Facebook.</p>
	<a name="facebook-learnmore"></a>
	<h2 class="learnMore">How does Facebook posting work?</h2>
  <hr class="dots" />
  <p>If you check the box to have your split times posted to Facebook you will have to log in to Facebook and give permission to the app to continue.
	If you are not logged to Facebook you will first see the Facebook login page, if you are already logged in you will go directly to the 
	page where you will give the Runner Tracking Facebook app permission to post on your wall.</p>
<p>Once you are on the Runner Tracking app page you have 
	the option to decide who can see the posts from the Runner Tracking Facebook app. After you have granted the app access to your wall 
	you will be directed back to the runner tracking site where you can input your payment information and finish the registration process.</p>
	<h2 class="learnMore">How does Twitter posting work?</h2>
  <hr class="dots" />
  <p>If you check the box to have your split times tweeted you will have to log in to Twitter and give permission to the app to continue.
	If you are not logged to Twitter you will first see the Twitter login page, if you are already logged in you will go directly to the 
	page where you will give the Runner Tracking Twitter app permission to tweet for you.</p>
<p>After you have granted the app access to your tweets 
	you will be directed back to the runner tracking site where you can input your payment information and finish the registration process.</p>
  <h2 class="learnMore"> That's all it costs? No other hidden fees?</h2>
  <hr class="dots" />
  <p>Nope. that's it. The only extra fees you will see are if you get charged by your cellular provider for receiving text
    messages. They might charge you, but we won't. If you're not sure, check with your provider before signing up.</p>
  <h2 class="learnMore">Okay, I'm convinced... How do I get started?</h2>
  <hr class="dots" />
  <p> It's simple. To track an athlete, you can enter the person's name in the box on the home page, or click on the <a href="../events/trackathlete">Track</a> link. If you would like to have your friends or family track you during the event, click on the <a href="../events/betrackedstep1">Be Tracked</a> link.</p>
  <h2 class="learnMore"> Help! I have one of the cellular providers you mention in your supported carrier list, but I never received a confirmation text... What's up? </h2>
  <hr class="dots" />
  <p>If you do not receive a verification code, then unfortunately, your phone, carrier or service is not compatible with Competitor 
    Wireless. Your service may be blocking "Premium" Content from short-codes as well. If you normally receive text messages without 
    a problem, but are not getting the verification code, please contact your Cellular provider to find out why you did not 
    receive any messages from us (short code: 85007).</p>
  <h2 class="learnMore"> Do you support International phones?</h2>
  <hr class="dots" />
  <p> At this time, we do not currently support International carriers, including Canada and Mexico. We are working on fixing this 
    issue and will hopefully open up our service to International providers soon.</p>
  <p>That's all there is to it. We'll walk you through 3 easy steps, then collect your payment information. We are using 
    Paypal&trade; to process all our credit card payments, so you can be confident that your information is secure with us. </p>
  <h2 class="learnMore"> I would like to send my participant flowers at the finish line. Do you provide that service? </h2>
  <hr class="dots" />
  <p> Currently we do not support flowers. We are always looking for new business opportunities though, and may one day roll
    out this service.</p>
  <h2 class="learnMore"> Can I get my finish times faxed to me? </h2>
  <hr class="dots" />
  <p> No, we will not fax your times to you</p>
  <h2 class="learnMore"> I sent an invitation out but the person never got it, what can I do?</h2>
  <hr class="dots" />
  <p> You can manage your email invitations at any time by logging into your account from the "Log In" link in the top menu 
    at any time.<br />
    - You can see the status of all invites you've currently sent (pending, accepted, declined).<br />
    - You can update/add or delete addresses that have not yet confirmed.<br />
    - You can have invitations resent from your own email address if someone has not received them from us.</p>
  <h2 class="learnMore"> I'm having trouble verifying my cell phone in Step 2</h2>
  <hr class="dots" />
  <p>Please confirm the verification code you are entering on the website, so that we can check it against what we show as 
    being sent. The code will originate from our short-number: 85007. The activation code will be 4 characters 
    (letters and numbers).</p>
  <div class="brclear"></div>
</div>
<!-- </main> -->