<?php $this->headTitle('Competitor Wireless - Privacy Policy'); ?>

<!-- <tout> -->
<div class="tout">
  <h2> Privacy Policy</h2>
  <div class="brclear"></div>
</div>
<!-- </tout> --> 

<!-- <main> -->
<div class="main">
    <p>Our postal address is <br />
      <strong>9477 Waples St<br />
      San Diego, CA 92121</strong></p>
    <p>We can be reached via e-mail at <a href="mailto:support@competitorwireless.com">support@competitorwireless.com</a><br />
    or you can reach us by telephone at 858-768-6760</p>
    <p>For each visitor to our Web page, our Web server automatically recognizes only the consumer's domain name, but 
      not the e-mail address (where possible).</p>
    <p>We collect only the domain name, but not the e-mail address of visitors to our Web page, aggregate information on 
      what pages consumers access or visit, information volunteered by the consumer, such as survey information and/or site 
      registrations, name and address, telephone number, payment information (e.g., credit card number and billing address).</p>
    <p>The information we collect is used for internal review and is then discarded, used to improve the content of our Web page,
      disclosed when legally required to do so, at the request of governmental authorities conducting an investigation, to verify 
      or enforce compliance with the policies governing our Website and applicable laws or to protect against misuse or unauthorized 
      use of our Website, to a successor entity in connection with a corporate merger, consolidation, sale of assets or other corporate
      change respecting the Website.</p>
    <p>With respect to cookies: We do not set any cookies.</p>
    <p>If you do not want to receive e-mail from us in the future, 
      please let us know by writing to us at the above address.</p>
    <p>We will never make the e-mail addresses or cellular phone numbers of those who access our site available to other
      organizations.</p>
    <p>If you supply us with your postal address on-line you will only receive the information for which you provided us your 
      address.</p>
    <p>Persons who supply us with their telephone numbers on-line will only receive telephone contact from us with information 
      regarding orders they have placed on-line.</p>
    <p>With respect to Ad Servers: We do not partner with or have special relationships with any ad server companies. </p>
    <p>From time to time, we may use customer information for new, unanticipated uses not previously disclosed in our privacy notice.  
      If our information practices change at some time in the future we will post the policy changes to our Web site to notify you of 
      these changes and provide you with the ability to opt out of these new uses.  If you are concerned about how your information is 
      used, you should check back at our Web site periodically.</p>
    <p>Customers may prevent their information from being used for purposes other than those for which it was originally collected 
      by writing to us at the above address.</p>
    <p>Upon request we provide site visitors with access to a description of information that we maintain about them.</p>
    <p>Consumers can access this information by writing to us at the above address.</p>
    <p>With respect to security: When we transfer and receive certain types of sensitive information such as financial or health 
      information, we redirect visitors to a secure server and will notify visitors through a pop-up screen on our site, We have appropriate 
      security measures in place in our physical facilities to protect against the loss, misuse or alteration of information that we have 
      collected from you at our site.</p>
    <p>If you feel that this site is not following its stated information policy, you may contact us at the above addresses or phone 
      number, The DMA's Committee on Ethical Business Practices at <a href="mailto:mgoldberger@the-dma.org">mgoldberger@the-dma.org</a>, 
      state or local chapters of the Better Business Bureau.</p>    
</div>
<div class="brclear"></div>
<!-- </main> -->