<?php $this->headTitle('Competitor Wireless - Learn More'); ?>

<!-- <tout> -->

<div class="tout">
  <h2> Learn More</h2>
  <div class="brclear"></div>
</div>
<!-- </tout> --> 

<!-- <main> -->
<div class="main">
  <h2>Wireless Rates &amp; Information</h2>
  <p><strong>Competitor Wireless Alerts</strong></p>
<p>    Competitor Wireless will deliver SMS messages to spectators throughout the race with the times of athletes they are following. 
    We will send out between 8-10 messages throughout the event.<br />
    All messages will be received from short code: <strong>85007. Message and Data Rates may apply</strong>, depending on your cellular plan.</p>
    
   <p> You can text <strong>HELP to 85007</strong> to more information or <strong>STOP to 85007</strong> to end service.</p>
    
   <p> You can view our Terms of Service <a href="https://www.competitorwireless.com/web/index/terms">here</a></p>
</div>
<div class="brclear"></div>
<!-- </main> -->